package clasesHibernate;
// Generated 12 dic 2024 8:47:50 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Hospitales generated by hbm2java
 */
public class Hospitales implements java.io.Serializable {

	private Integer idHospital;
	private Provincias provincias;
	private String nombre;
	private Set ictuses = new HashSet(0);

	public Hospitales() {
	}

	public Hospitales(Provincias provincias, String nombre, Set ictuses) {
		this.provincias = provincias;
		this.nombre = nombre;
		this.ictuses = ictuses;
	}

	public Integer getIdHospital() {
		return this.idHospital;
	}

	public void setIdHospital(Integer idHospital) {
		this.idHospital = idHospital;
	}

	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getIctuses() {
		return this.ictuses;
	}

	public void setIctuses(Set ictuses) {
		this.ictuses = ictuses;
	}

}
