package clasesHibernate;
// Generated 12 dic 2024 8:47:50 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Ictus generated by hbm2java
 */
public class Ictus implements java.io.Serializable {

	private Integer idIctus;
	private Hospitales hospitales;
	private Date fechaIngreso;
	private Integer edad;
	private String sexo;

	public Ictus() {
	}

	public Ictus(Hospitales hospitales, Date fechaIngreso, Integer edad, String sexo) {
		this.hospitales = hospitales;
		this.fechaIngreso = fechaIngreso;
		this.edad = edad;
		this.sexo = sexo;
	}

	public Integer getIdIctus() {
		return this.idIctus;
	}

	public void setIdIctus(Integer idIctus) {
		this.idIctus = idIctus;
	}

	public Hospitales getHospitales() {
		return this.hospitales;
	}

	public void setHospitales(Hospitales hospitales) {
		this.hospitales = hospitales;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

}
