package clasesHibernate;
// Generated 12 dic 2024 8:47:50 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private Integer idProvincia;
	private String nombre;
	private Set hospitaleses = new HashSet(0);

	public Provincias() {
	}

	public Provincias(String nombre, Set hospitaleses) {
		this.nombre = nombre;
		this.hospitaleses = hospitaleses;
	}

	public Integer getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(Integer idProvincia) {
		this.idProvincia = idProvincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getHospitaleses() {
		return this.hospitaleses;
	}

	public void setHospitaleses(Set hospitaleses) {
		this.hospitaleses = hospitaleses;
	}

}
